# This file was generated by GoReleaser. DO NOT EDIT.
cask "ddogo" do
  name "ddogo"
  desc "Lightweight CLI for consuming Datadog logs."
  homepage "https://github.com/gabrielmbmb/ddogo"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ddogo"

  on_macos do
    on_intel do
      url "https://github.com/gabrielmbmb/ddogo/releases/download/v#{version}/ddogo_#{version}_darwin_amd64.tar.gz"
      sha256 "a90dba12f6304cac119e9984e590e4b5528f73bec061617d2f18fd84b0c2ef9a"
    end
    on_arm do
      url "https://github.com/gabrielmbmb/ddogo/releases/download/v#{version}/ddogo_#{version}_darwin_arm64.tar.gz"
      sha256 "2aa2c99f67e86993a278b2469327f668ec10a0d6d428ca51b94f410053b44c76"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gabrielmbmb/ddogo/releases/download/v#{version}/ddogo_#{version}_linux_amd64.tar.gz"
      sha256 "abd701df008361c93f8b7c3df5c2a5b7ca7389b1ae4cbba48cf8fcfe6c0ac59b"
    end
    on_arm do
      url "https://github.com/gabrielmbmb/ddogo/releases/download/v#{version}/ddogo_#{version}_linux_arm64.tar.gz"
      sha256 "3840b452e62237d82233d894ea19cb2a0411b0d92cc5052ffff2fb80b19e94a3"
    end
  end

  postflight do
    system_command "/bin/sh", args: ["-c", "xattr -d com.apple.quarantine '#{staged_path}/ddogo' 2>/dev/null || true"]
  end

  # No zap stanza required
end
