# This file was generated by GoReleaser. DO NOT EDIT.
cask "ddogo" do
  name "ddogo"
  desc "Lightweight CLI for consuming Datadog logs, spans, RUM events, metrics, and Error Tracking issues."
  homepage "https://github.com/gabrielmbmb/ddogo"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ddogo"

  on_macos do
    on_intel do
      url "https://github.com/gabrielmbmb/ddogo/releases/download/v#{version}/ddogo_#{version}_darwin_amd64.tar.gz"
      sha256 "e4c6adeac1b4d32128c5b45360ddd392b428e0faf711ccbeaa7a50251785d488"
    end
    on_arm do
      url "https://github.com/gabrielmbmb/ddogo/releases/download/v#{version}/ddogo_#{version}_darwin_arm64.tar.gz"
      sha256 "f6806300026e4a338728bc2c1a928c114468bd94b3c338460cef77281efe8b24"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gabrielmbmb/ddogo/releases/download/v#{version}/ddogo_#{version}_linux_amd64.tar.gz"
      sha256 "5a8fea0a42a30a4186124bf9e76fc72ca9169bcf6821e5058d992c097f2baf81"
    end
    on_arm do
      url "https://github.com/gabrielmbmb/ddogo/releases/download/v#{version}/ddogo_#{version}_linux_arm64.tar.gz"
      sha256 "6457c273e501864a373404143358bb589198b17c60794f745dd14952c7544c13"
    end
  end

  postflight do
    system_command "/bin/sh", args: ["-c", "xattr -d com.apple.quarantine '#{staged_path}/ddogo' 2>/dev/null || true"]
  end

  # No zap stanza required
end
