# This file was generated by GoReleaser. DO NOT EDIT.
cask "what-ttft" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "010ef69e0fb31c909c8e9cc9dcadd70cbedaa145d87336be91fde7501e1dbe15"
      url "https://github.com/gabrielmbmb/what-ttft/releases/download/v#{version}/what-ttft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b3714759182e56711e4fcc4f1e057fc62b7e4e5b879f1ce920f2473895934cae"
      url "https://github.com/gabrielmbmb/what-ttft/releases/download/v#{version}/what-ttft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c600e5cacee5014eaffe46ed0e39f938ecfef37d0b1a731fa1fe0d789ce547cc"
      url "https://github.com/gabrielmbmb/what-ttft/releases/download/v#{version}/what-ttft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0bc2dc605a76cdb0582db3186535a00e4513884878fe3c2f874054ef3ef731d9"
      url "https://github.com/gabrielmbmb/what-ttft/releases/download/v#{version}/what-ttft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "what-ttft"
  desc "Benchmark latency in LLM, TTS, and STT APIs."
  homepage "https://github.com/gabrielmbmb/what-ttft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "what-ttft"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/what-ttft"]
    end
  end

  # No zap stanza required

end
