# This file was generated by GoReleaser. DO NOT EDIT.
cask "what-ttft" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "75d4b6c35e2ea4be81100a7fc75d0e5b2bea9cab3e15d655b01516df9fc24b28"
      url "https://github.com/gabrielmbmb/what-ttft/releases/download/v#{version}/what-ttft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ffe67899b8ab6dceafd441fe6c3dd2eda57e860ed69389d3806b26a1a6570fb5"
      url "https://github.com/gabrielmbmb/what-ttft/releases/download/v#{version}/what-ttft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7d076bcf9af68905791a6a09d598c45c1ead0093f5c23b853e04655663944774"
      url "https://github.com/gabrielmbmb/what-ttft/releases/download/v#{version}/what-ttft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba61b0e59400ee7177cf74f82b645095911e6413fa0438f211342ad8d8f1b789"
      url "https://github.com/gabrielmbmb/what-ttft/releases/download/v#{version}/what-ttft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "what-ttft"
  desc "Benchmark latency in LLM, TTS, and STT APIs."
  homepage "https://github.com/gabrielmbmb/what-ttft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "what-ttft"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/what-ttft"]
    end
  end

  # No zap stanza required

end
