# This file was generated by GoReleaser. DO NOT EDIT.
cask "what-ttft" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f5ea0dcfbf43787b070d2e8a7cf17a19f55048d30af1d6cbc363e5d1f568d935"
      url "https://github.com/gabrielmbmb/what-ttft/releases/download/v#{version}/what-ttft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f18c374ee2f3b59f449fcc9a5bcd18dacff84f0296877461c4b29909a12b0d56"
      url "https://github.com/gabrielmbmb/what-ttft/releases/download/v#{version}/what-ttft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "618fa135b14a4ad2e3d2b2cc33e9b6d2243caee4fd0babb50b9fa1e31763a3a3"
      url "https://github.com/gabrielmbmb/what-ttft/releases/download/v#{version}/what-ttft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "be3e9056ae4cf92cbbe72746b7a15128be8e060f2b9a22d61897ea5255c5841f"
      url "https://github.com/gabrielmbmb/what-ttft/releases/download/v#{version}/what-ttft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "what-ttft"
  desc "Benchmark latency in LLM, TTS, and STT APIs."
  homepage "https://github.com/gabrielmbmb/what-ttft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "what-ttft"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/what-ttft"]
    end
  end

  # No zap stanza required

end
